### ISSUE TITLE
image-picker-(gallery): selected image is not the same as processed image

### ISSUE THREAD

**Issue by k3b** [yaa110/Piclice#2]
in the image-picker-(gallery) i can see several preview-images. In some cases the selected image is not the same as the processed image.

example: i pick a three and get a slice of a house.

i was able to reproduce this in 3 out of 10 tries.

maybe it is helpful if the SetSliceProcessingOptions-Dialog would display the image to be sliced.

Also note that the picker displays many douplicates of images although i have no duplicates on the device.

example: I have found the tree image 8 times in the picker although there is only one copy of it

**Comment by k3b** [comment]
in ImageAdapter::getView() holder.id is not reset in case that viewitem is recicled

change from 

    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {
        final ViewHolder holder;
        if (convertView == null) {
            convertView = View.inflate(context, R.layout.thumbnail, null);
            holder = new ViewHolder();
            holder.imageView = (ImageView) convertView.findViewById(R.id.image);
            holder.view = convertView.findViewById(R.id.holder);
            holder.id = thumbnails[position];
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }

to

    @Override
    public View getView(final int position, View convertView, ViewGroup parent) {
        final ViewHolder holder;
        if (convertView == null) {
            convertView = View.inflate(context, R.layout.thumbnail, null);
            holder = new ViewHolder();
            holder.imageView = (ImageView) convertView.findViewById(R.id.image);
            holder.view = convertView.findViewById(R.id.holder);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }
        holder.id = thumbnails[position];

should fix the problem

**Comment by yaa110** [comment]
Your change was added, Thanks.
I couldn't reproduce the second issue (i.e. displaying many duplicates of images). Please comment your device model and SDK version.

Regards,

**Comment by k3b** [comment]
i am using an android-4.4 cellphone. the second issue "many times the same image" is an other symptom of the same bug so it should be gone, too

**Comment by yaa110** [comment]
Thanks
